apiVersion: v1
kind: Service
metadata:
  name: dockermanager-backend
  namespace: dockermanager
  labels:
    app: dockermanager-backend
spec:
  ports:
  - port: 5000
    targetPort: 5000
    name: http
  selector:
    app: dockermanager-backend
  type: ClusterIP
