apiVersion: v1
kind: Secret
metadata:
  name: dockermanager-secrets
  namespace: dockermanager
type: Opaque
data:
  JWT_SECRET: c3VwZXJzZWNyZXQxMjM= # "supersecret123"
  GEMINI_API_KEY: QUl6YVN5REF2VHhnNzUyTkg5VHlNRU1nZElNZV9oYkVHXzdyTUxn # "AIzaSyDAvTxg752NH9TyMEMgdIMe_hbEG_7rMLg"
  SENDGRID_API_KEY: U0cubEIwclpYdE5Rb1N4Zng3S1BfWjBxdy51U3QyQVFUTnpBMmdnVHpoQlFid2NOa0ZBNC1yUGhtNnU4NzMyUk4zN1Bj # "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"
  MINIO_ROOT_USER: YWRtaW4= # "admin"
  MINIO_ROOT_PASSWORD: Q0hBTkdFX01FX1NUUk9OR19QQVNTV09SRA== # "CHANGE_ME_STRONG_PASSWORD"
